set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports D]
set_property IOSTANDARD LVCMOS33 [get_ports Q]
set_property PACKAGE_PIN N20 [get_ports Q]
set_property PACKAGE_PIN R17 [get_ports D]
set_property PACKAGE_PIN W14 [get_ports clk]
